/**
 * Extension Detector - Detect if running in Chrome Extension context
 *
 * Replay URLs are generated by the extension, but the hosted player can also be
 * opened directly during development. This helper keeps mode detection and Drive
 * URL shaping outside the shared player runtime.
 */

declare const chrome:
  | {
      runtime?: { getURL?: (path: string) => string };
    }
  | undefined;

export function isExtensionContext(): boolean {
  return (
    typeof chrome !== "undefined" &&
    chrome.runtime !== undefined &&
    typeof chrome.runtime.getURL === "function"
  );
}

export function detectMode(): "extension" | "standalone" {
  if (isExtensionContext()) {
    return "extension";
  }
  return "standalone";
}

export function getBaseUrl(): string {
  // Replay always runs on the hosted player origin (or local Vite). The
  // extension no longer ships player assets under chrome-extension://.
  return "./";
}

export function getDriveFileUrl(fileId: string): string {
  // For video preview/stream
  return `https://drive.google.com/file/d/${fileId}/preview`;
}

export function getDriveDownloadUrl(fileId: string): string {
  // Standalone player proxies Drive downloads through the same Pages origin to avoid browser CORS/CORP issues.
  return `/api/drive?id=${encodeURIComponent(fileId)}`;
}
