/**
 * Property-based tests for the player's ZIP central-directory parser.
 *
 * These tests target {@link parseZipCentralDirectory}, a pure, importable
 * function that performs only the synchronous structural parse of a ZIP byte
 * buffer (no decompression, decryption, or CRC validation). Because it is total
 * and non-throwing, its safety invariant can be checked across a wide range of
 * generated byte buffers, including empty and truncated inputs.
 *
 * fast-check and Vitest are added as dev dependencies in a later task (task 9),
 * so the imports below may surface a resolution warning until then. The global
 * fast-check configuration (numRuns, verbose, seed reporting) is applied via
 * the root `test/property-config.ts` setup file.
 */
import fc from "fast-check";
import { describe, expect, it } from "vitest";
import { parseZipCentralDirectory, type ZipParseResult } from "./zip-parser";

const EOCD_SIGNATURE = 0x06054b50;

/**
 * Build a byte buffer that ends with a valid-looking EOCD signature so the
 * generator also exercises the central-directory walking code paths (not just
 * the early "EOCD not found" rejection). The surrounding bytes are arbitrary,
 * so the entry count and central-directory offset are effectively random and
 * drive the parser through its bounds-checked, typed-error branches.
 */
function withEocdSignature(prefix: Uint8Array, tail: Uint8Array): Uint8Array {
  const buffer = new Uint8Array(prefix.length + 4 + tail.length);
  buffer.set(prefix, 0);
  // Little-endian EOCD signature.
  buffer[prefix.length] = EOCD_SIGNATURE & 0xff;
  buffer[prefix.length + 1] = (EOCD_SIGNATURE >>> 8) & 0xff;
  buffer[prefix.length + 2] = (EOCD_SIGNATURE >>> 16) & 0xff;
  buffer[prefix.length + 3] = (EOCD_SIGNATURE >>> 24) & 0xff;
  buffer.set(tail, prefix.length + 4);
  return buffer;
}

describe("parseZipCentralDirectory", () => {
  /**
   * Generator covering the full input space of byte buffers:
   *  - arbitrary buffers (empty, tiny/truncated, and large) via `fc.uint8Array`,
   *  - buffers that embed a valid EOCD signature to drive central-directory
   *    walking with arbitrary (often out-of-bounds) counts and offsets.
   */
  const byteBufferArbitrary = fc.oneof(
    fc.uint8Array({ minLength: 0, maxLength: 1024 }),
    fc
      .tuple(
        fc.uint8Array({ minLength: 0, maxLength: 256 }),
        fc.uint8Array({ minLength: 0, maxLength: 64 }),
      )
      .map(([prefix, tail]) => withEocdSignature(prefix, tail)),
  );

  /**
   * Property 9: ZIP/CRC parsing safety.
   *
   * For ANY byte buffer, the parser returns either a valid entry list or a
   * typed error value, and NEVER throws an uncaught exception. The result is
   * always a well-formed discriminated union: `ok: true` with an array of
   * entries, or `ok: false` with a typed error code and message.
   *
   * **Validates: Requirements 5.9**
   */
  it("never throws and always returns the typed result/error union (Property 9: ZIP/CRC parsing safety)", () => {
    fc.assert(
      fc.property(byteBufferArbitrary, (bytes) => {
        let result: ZipParseResult;
        // The parser must never throw for any byte buffer input.
        expect(() => {
          result = parseZipCentralDirectory(bytes);
        }).not.toThrow();

        // The result is always the well-formed discriminated union.
        // biome-ignore lint/style/noNonNullAssertion: assigned above when no throw occurred.
        const value = result!;
        expect(typeof value.ok).toBe("boolean");
        if (value.ok) {
          expect(Array.isArray(value.entries)).toBe(true);
        } else {
          expect(typeof value.code).toBe("string");
          expect(typeof value.message).toBe("string");
          expect(value.code.length).toBeGreaterThan(0);
        }
      }),
    );
  });

  /**
   * Specialization of Property 9 for empty, truncated, and malformed buffers:
   * these inputs must yield a typed error (`ok: false`) rather than a success,
   * confirming the parser rejects structurally invalid input safely.
   *
   * **Validates: Requirements 5.9**
   */
  it("returns a typed error for empty/truncated/malformed buffers (Property 9: ZIP/CRC parsing safety)", () => {
    // Empty buffers and buffers smaller than the minimum EOCD record (22 bytes)
    // are always truncated/malformed and can never parse successfully.
    fc.assert(
      fc.property(fc.uint8Array({ minLength: 0, maxLength: 21 }), (bytes) => {
        const result = parseZipCentralDirectory(bytes);
        expect(result.ok).toBe(false);
        if (!result.ok) {
          expect(typeof result.code).toBe("string");
          expect(result.code.length).toBeGreaterThan(0);
        }
      }),
    );
  });
});

/**
 * Example-based unit tests for {@link parseZipCentralDirectory} using small,
 * hand-built in-memory ZIP byte buffers.
 *
 * Where the property test above checks the safety invariant across arbitrary
 * inputs, these tests construct *structurally valid* archives that mirror the
 * byte layout written by the offscreen recorder (`src/offscreen/offscreen.ts`)
 * and read by the standalone player (`public/player.js`):
 *
 *  - STORED entries (compression method 0): payload bytes equal the content,
 *    so `compressedSize === uncompressedSize`.
 *  - DEFLATE entries (compression method 8): payload bytes are a real
 *    `deflate-raw` stream (a single final stored DEFLATE block), so the
 *    parser reports method 8 with a distinct compressed size.
 *  - Optional artifacts (`console.json`, `network.json`, `websocket.json`) are
 *    detected present/absent by entry name, matching how the player resolves
 *    package entries via name lookup.
 */

/** Polynomial CRC-32 (IEEE) used to populate realistic ZIP header checksums. */
function crc32(bytes: Uint8Array): number {
  let crc = 0xffffffff;
  for (let i = 0; i < bytes.length; i += 1) {
    crc ^= bytes[i];
    for (let bit = 0; bit < 8; bit += 1) {
      crc = (crc >>> 1) ^ (0xedb88320 & -(crc & 1));
    }
  }
  return (crc ^ 0xffffffff) >>> 0;
}

/**
 * Encode `data` as a real, inflatable `deflate-raw` stream using a single final
 * *stored* (uncompressed) DEFLATE block. This is genuine DEFLATE output — a
 * browser `DecompressionStream("deflate-raw")` inflates it back to `data` — but
 * needs no compression library, keeping the fixture self-contained.
 */
function rawDeflateStored(data: Uint8Array): Uint8Array {
  const len = data.length; // stored blocks cap at 65535 bytes; fixtures are tiny.
  const out = new Uint8Array(5 + len);
  out[0] = 0x01; // BFINAL=1, BTYPE=00 (stored / no compression)
  out[1] = len & 0xff;
  out[2] = (len >>> 8) & 0xff;
  out[3] = ~len & 0xff;
  out[4] = (~len >>> 8) & 0xff;
  out.set(data, 5);
  return out;
}

const LOCAL_FILE_HEADER_SIGNATURE = 0x04034b50;
const CENTRAL_DIRECTORY_SIGNATURE = 0x02014b50;
const ZIP_METHOD_STORE = 0 as const;
const ZIP_METHOD_DEFLATE = 8 as const;

interface FixtureEntry {
  name: string;
  content: Uint8Array;
  method: typeof ZIP_METHOD_STORE | typeof ZIP_METHOD_DEFLATE;
}

/**
 * Assemble a structurally valid ZIP byte buffer (local file headers, central
 * directory, EOCD) from the given entries, mirroring the writer layout in
 * `src/offscreen/offscreen.ts`.
 */
function buildZip(entries: FixtureEntry[]): Uint8Array {
  const encoder = new TextEncoder();
  const prepared = entries.map((entry) => {
    const nameBytes = encoder.encode(entry.name);
    const payload =
      entry.method === ZIP_METHOD_DEFLATE ? rawDeflateStored(entry.content) : entry.content;
    return { ...entry, nameBytes, payload, crc: crc32(entry.content) };
  });

  const locals: Uint8Array[] = [];
  const centrals: Uint8Array[] = [];
  const localOffsets: number[] = [];
  let offset = 0;

  for (const p of prepared) {
    localOffsets.push(offset);
    const header = new Uint8Array(30 + p.nameBytes.length);
    const view = new DataView(header.buffer);
    view.setUint32(0, LOCAL_FILE_HEADER_SIGNATURE, true);
    view.setUint16(4, 20, true); // version needed
    view.setUint16(6, 0, true); // flags
    view.setUint16(8, p.method, true);
    view.setUint16(10, 0, true); // mod time
    view.setUint16(12, 0, true); // mod date
    view.setUint32(14, p.crc, true);
    view.setUint32(18, p.payload.length, true); // compressed size
    view.setUint32(22, p.content.length, true); // uncompressed size
    view.setUint16(26, p.nameBytes.length, true);
    view.setUint16(28, 0, true); // extra length
    header.set(p.nameBytes, 30);
    locals.push(header, p.payload);
    offset += header.length + p.payload.length;
  }

  const centralStart = offset;
  prepared.forEach((p, index) => {
    const header = new Uint8Array(46 + p.nameBytes.length);
    const view = new DataView(header.buffer);
    view.setUint32(0, CENTRAL_DIRECTORY_SIGNATURE, true);
    view.setUint16(4, 20, true); // version made by
    view.setUint16(6, 20, true); // version needed
    view.setUint16(8, 0, true); // flags
    view.setUint16(10, p.method, true);
    view.setUint16(12, 0, true); // mod time
    view.setUint16(14, 0, true); // mod date
    view.setUint32(16, p.crc, true);
    view.setUint32(20, p.payload.length, true); // compressed size
    view.setUint32(24, p.content.length, true); // uncompressed size
    view.setUint16(28, p.nameBytes.length, true);
    view.setUint16(30, 0, true); // extra length
    view.setUint16(32, 0, true); // comment length
    view.setUint16(34, 0, true); // disk number start
    view.setUint16(36, 0, true); // internal attrs
    view.setUint32(38, 0, true); // external attrs
    view.setUint32(42, localOffsets[index], true); // local header offset
    header.set(p.nameBytes, 46);
    centrals.push(header);
    offset += header.length;
  });

  const centralSize = offset - centralStart;
  const eocd = new Uint8Array(22);
  const eocdView = new DataView(eocd.buffer);
  eocdView.setUint32(0, 0x06054b50, true);
  eocdView.setUint16(4, 0, true); // disk number
  eocdView.setUint16(6, 0, true); // disk with central directory
  eocdView.setUint16(8, prepared.length, true); // entries on this disk
  eocdView.setUint16(10, prepared.length, true); // total entries
  eocdView.setUint32(12, centralSize, true);
  eocdView.setUint32(16, centralStart, true);
  eocdView.setUint16(20, 0, true); // comment length

  const parts = [...locals, ...centrals, eocd];
  const total = parts.reduce((sum, part) => sum + part.length, 0);
  const out = new Uint8Array(total);
  let pos = 0;
  for (const part of parts) {
    out.set(part, pos);
    pos += part.length;
  }
  return out;
}

/** Resolve a parsed entry by name, mirroring the player's name-based lookup. */
function findEntry(result: ZipParseResult, name: string) {
  if (!result.ok) return undefined;
  return result.entries.find((entry) => entry.name === name);
}

const REQUIRED_ENTRIES = ["recording-index.json", "manifest.json", "metadata.json"] as const;
const OPTIONAL_ARTIFACTS = ["console.json", "network.json", "websocket.json"] as const;

describe("parseZipCentralDirectory (example fixtures)", () => {
  const encoder = new TextEncoder();

  it("reads metadata for a STORED (method 0) entry", () => {
    const content = encoder.encode(JSON.stringify({ phase: "idle" }));
    const zip = buildZip([{ name: "metadata.json", content, method: ZIP_METHOD_STORE }]);

    const result = parseZipCentralDirectory(zip);

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.entries).toHaveLength(1);
    const [entry] = result.entries;
    expect(entry.name).toBe("metadata.json");
    expect(entry.compressionMethod).toBe(ZIP_METHOD_STORE);
    // Stored entries are not compressed, so the sizes match exactly.
    expect(entry.uncompressedSize).toBe(content.length);
    expect(entry.compressedSize).toBe(content.length);
    expect(entry.crc32).toBe(crc32(content));
    expect(entry.isEncrypted).toBe(false);
  });

  it("reads metadata for a DEFLATE (method 8) entry", () => {
    const content = encoder.encode(JSON.stringify({ logs: [1, 2, 3], note: "compress me" }));
    const zip = buildZip([{ name: "console.json", content, method: ZIP_METHOD_DEFLATE }]);

    const result = parseZipCentralDirectory(zip);

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.entries).toHaveLength(1);
    const [entry] = result.entries;
    expect(entry.name).toBe("console.json");
    expect(entry.compressionMethod).toBe(ZIP_METHOD_DEFLATE);
    // Uncompressed size still reflects the original content length...
    expect(entry.uncompressedSize).toBe(content.length);
    // ...while the compressed payload is the deflate-raw stream (distinct size).
    expect(entry.compressedSize).toBe(rawDeflateStored(content).length);
    expect(entry.crc32).toBe(crc32(content));
    expect(entry.isEncrypted).toBe(false);
  });

  it("parses a multi-entry package mixing stored and deflate entries", () => {
    const json = (value: unknown) => encoder.encode(JSON.stringify(value));
    const zip = buildZip([
      { name: "recording-index.json", content: json({ v: 1 }), method: ZIP_METHOD_DEFLATE },
      { name: "manifest.json", content: json({ artifacts: {} }), method: ZIP_METHOD_DEFLATE },
      { name: "metadata.json", content: json({ phase: "idle" }), method: ZIP_METHOD_DEFLATE },
      {
        name: "video.part-000.webm",
        content: new Uint8Array([0x1a, 0x45, 0xdf, 0xa3]),
        method: ZIP_METHOD_STORE,
      },
    ]);

    const result = parseZipCentralDirectory(zip);

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.entries.map((entry) => entry.name)).toEqual([
      "recording-index.json",
      "manifest.json",
      "metadata.json",
      "video.part-000.webm",
    ]);
    // The already-compressed video part is stored verbatim (method 0)...
    expect(findEntry(result, "video.part-000.webm")?.compressionMethod).toBe(ZIP_METHOD_STORE);
    // ...while text artifacts use DEFLATE (method 8).
    expect(findEntry(result, "manifest.json")?.compressionMethod).toBe(ZIP_METHOD_DEFLATE);
  });

  it("detects optional artifacts when present", () => {
    const json = (value: unknown) => encoder.encode(JSON.stringify(value));
    const zip = buildZip([
      ...REQUIRED_ENTRIES.map(
        (name): FixtureEntry => ({ name, content: json({ name }), method: ZIP_METHOD_DEFLATE }),
      ),
      ...OPTIONAL_ARTIFACTS.map(
        (name): FixtureEntry => ({
          name,
          content: json({ name, entries: [] }),
          method: ZIP_METHOD_DEFLATE,
        }),
      ),
    ]);

    const result = parseZipCentralDirectory(zip);

    expect(result.ok).toBe(true);
    for (const name of REQUIRED_ENTRIES) {
      expect(findEntry(result, name)).toBeDefined();
    }
    for (const name of OPTIONAL_ARTIFACTS) {
      expect(findEntry(result, name)).toBeDefined();
    }
  });

  it("reports optional artifacts as absent when omitted", () => {
    const json = (value: unknown) => encoder.encode(JSON.stringify(value));
    const zip = buildZip(
      REQUIRED_ENTRIES.map(
        (name): FixtureEntry => ({ name, content: json({ name }), method: ZIP_METHOD_DEFLATE }),
      ),
    );

    const result = parseZipCentralDirectory(zip);

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    // Required entries are still present...
    for (const name of REQUIRED_ENTRIES) {
      expect(findEntry(result, name)).toBeDefined();
    }
    // ...but the optional artifacts are simply not in the entry list.
    for (const name of OPTIONAL_ARTIFACTS) {
      expect(findEntry(result, name)).toBeUndefined();
    }
    expect(result.entries).toHaveLength(REQUIRED_ENTRIES.length);
  });

  it("produces DEFLATE payloads that inflate back to the original content", async () => {
    if (typeof DecompressionStream !== "function") return; // environment guard

    const content = encoder.encode(JSON.stringify({ message: "real deflate bytes" }));
    const zip = buildZip([{ name: "network.json", content, method: ZIP_METHOD_DEFLATE }]);

    const result = parseZipCentralDirectory(zip);
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const entry = result.entries[0];

    // Walk from the parsed local-header offset to the payload, mirroring the
    // player's unzipStoredPackage/readZipEntryBytes flow, then inflate it.
    const headerView = new DataView(zip.buffer, zip.byteOffset, zip.byteLength);
    const nameLength = headerView.getUint16(entry.localHeaderOffset + 26, true);
    const extraLength = headerView.getUint16(entry.localHeaderOffset + 28, true);
    const payloadStart = entry.localHeaderOffset + 30 + nameLength + extraLength;
    const payload = zip.subarray(payloadStart, payloadStart + entry.compressedSize);

    // Copy into a fresh ArrayBuffer-backed view so it is a valid chunk.
    const payloadCopy = new Uint8Array(payload);
    // Feed the bytes straight into the decompression stream's writable side.
    // (jsdom's Blob does not implement `.stream()`, so avoid Blob here.)
    const decompressor = new DecompressionStream("deflate-raw");
    const writer = decompressor.writable.getWriter();
    void writer.write(payloadCopy);
    void writer.close();
    const inflated = new Uint8Array(await new Response(decompressor.readable).arrayBuffer());

    expect(inflated.length).toBe(entry.uncompressedSize);
    expect(Array.from(inflated)).toEqual(Array.from(content));
  });
});
